title: INK PRODUCTION BLOG
description: "INK PRODUCTIONの公式ブログ。デザイン、マーケ、AIなどのトピックを発信"
baseurl: "/ink-production-site"
url: "https://inkproduction1400-bot.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
permalink: /:year/:month/:day/:title.html